### ISSUE TITLE
Module: 

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/class-work#12]
# Assignment Description
![image](https://github.com/quaternary-game/class-work/assets/60514384/15a88132-6ca4-45ac-b94a-29bfe2840806)

# Team Assignments
Each of us pick 2-3 slides (one of us will have 3) to create and present. Someone combines the videos at the end.

Easiest way to store large files on github is git lfs or release tab. Kaltura might also work?

**Comment by adediu25** [comment]
I can take slides 5-6 if that sounds good

**Comment by IllustratedMan-code** [comment]
Fine with me

**Comment by ConnorMcKinney99** [comment]
I can take the first three.

**Comment by IllustratedMan-code** [comment]
4, 7

**Comment by john-whiting** [comment]
8, 7

**Comment by IllustratedMan-code** [comment]
# Project Abstract
This project is an educational videogame about genetics. Genetics is a broad topic, so it had to be constrained to fit a smaller set of concepts. To that end, this project is aimed at **high school aged children** that are taking a biology class.  A high school biology class covers genetics concepts that include **traits, alleles, genes, inheiritance, and evolution**. To ensure that this project can be used by the vast majority of its target audience, **accessibility** is a major constraint. To that end, this project will include **international language features**, **a mouse focused user interface**, and will take into account color-blind users.
