### ISSUE TITLE
Software Stack/Code Style

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/class-work#5]
# Game Engine
- Godot and GDscript
- Godot engine is the only thing you need, it includes the editor
- Lock version to 4.1 on steam (properties-> betas ->4.1)
## Image editor/asset creator
- Krita is pretty good (and free) for raster images (PNG/JPEG) (pixelart)
- Aesprite ($20) specialized pixelart app
- Inkscape is good for SVG images but harder to use than Krita

# Code style
- John wants that static typing! See the [docs](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/static_typing.html)
- Don't do anything super lazy (bad variable names, etc)
- I'll let John say more if needed

**Comment by IllustratedMan-code** [comment]
We need to determine a branching strategy, I vote for Github flow. 

It boils down to
- Open feature branch for your change (ideally linked with issue)
- make changes
- Make a pull request to main
- Get it reviewed by others
- Merge pull request
- Delete branch and close linked issue

**Comment by john-whiting** [comment]
> We need to determine a branching strategy, I vote for Github flow. 
> 
> It boils down to
> - Open feature branch for your change (ideally linked with issue)
> - make changes
> - Make a pull request to main
> - Get it reviewed by others
> - Merge pull request
> - Delete branch and close linked issue 

I'm open to other opinions, but I'm in favor of everything except the merge into main. I typically like to have a `develop` branch in there instead. This allows for more testing on a combined branch before saying it is final and updating main.

I.e., branch off develop, merge into develop.

Later on, there would be a release branch off of develop that can get merged into main.

**Comment by john-whiting** [comment]
I think https://github.com/quaternary-game/quaternary/pull/5 and https://github.com/quaternary-game/quaternary/pull/6 address these concerns nicely. Also, the project code is in a new repository now.
